# Generated by Django 3.1.13 on 2022-09-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211214_0753'),
        ('news', '0002_auto_20220113_1209'),
    ]

    operations = [
    ]
