# Generated by Django 3.2.7 on 2022-01-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prova_pratica_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='valore',
            field=models.FloatField(),
        ),
    ]
